### ISSUE TITLE
Action to catch dead links

### ISSUE THREAD

**Issue by robmarkcole** [acgeospatial/awesome-earthobservation-code#35]
This works well for me 

https://github.com/robmarkcole/satellite-image-deep-learning/blob/master/.github/workflows/action.yml

**Comment by acgeospatial** [comment]
oh brilliant - thank you. I'll give it a go

**Comment by acgeospatial** [comment]
OK got it working was seeing failures on 429 responses. So I've set an ignore pattern. https://github.com/acgeospatial/awesome-earthobservation-code/blob/master/.github/workflows/markdown.links.config.json borrowed from https://github.com/tcort/markdown-link-check#config-file-format I had to refer to it in my action.yml but test passes now. cheers for the heads up
